<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="<?=APP_CHARSET?>">
        <title>Manuals & Docs</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/css/docs.min.css?v=<?=$version?>" rel="stylesheet">
    </head>

    <body>
        <nav>
            <img alt="<?=$action_name?>" src="/img/kumbiaphp.svg">
        </nav>
        <div class="table">
            <aside>
                <?php View::partial('aside', false, ['list'=>Config::get("docs.$action_name.index"), 'titles'=>'h2']); ?>
            </aside>
            <main>
                <?php View::content() ?>
            </main>
        </div>
    </body>
</html>